export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';

export const GET_KEJUARAAN_SUCCESS = "GET_KEJUARAAN_SUCCESS";
export const GET_KEJUARAAN_FAIL = "GET_KEJUARAN_FAIL";

export const POST_KEJUARAAN_SUCCESS = "POST_KEJUARAAN_SUCCESS";
export const POST_KEJUARAAN_FAIL = "POST_KEJUARAAN_FAIL";

export const PATCH_KEJUARAAN_SUCCESS = "PATCH_KEJUARAAN_SUCCESS";
export const PATCH_KEJUARAAN_FAIL = "PATCH_KEJUARAAN_FAIL";

export const DELET_KEJUARAAN_SUCCESS = "DELET_KEJUARAAN_SUCCESS";
export const DELET_KEJUARAAN_FAIL = "DELET_KEJUARAAN_FAIL";

export const GET_DAFTAR_SUCCESS = "GET_DAFTAR_SUCCESS";
export const GET_DAFTAR_FAIL = "GET_DAFTAR_FAIL";

export const POST_DAFTAR_SUCCESS = "POST_DAFTAR_SUCCESS";
export const POST_DAFTAR_FAIL = "POST_DAFTAR_FAIL";

export const PATCH_DAFTAR_SUCCESS = "PATCH_DAFTAR_SUCCESS";
export const PATCH_DAFTAR_FAIL = "PATCH_DAFTAR_FAIL";

export const DELET_DAFTAR_SUCCESS = "DELET_DAFTAR_SUCCESS";
export const DELET_DAFTAR_FAIL = "DELET_DAFTAR_SUCCESS";

export const GET_TABLE_SUCCESS = "GET_TABLE_SUCCESS";
export const GET_TABLE_FAIL = "GET_TABLE_FAIL";

export const POST_TABLE_SUCCESS = "POST_TABLE_SUCCESS";
export const POST_TABLE_FAIL = "POST_TABLE_FAIL";

export const PATCH_TABLE_SUCCESS = "PATCH_TABLE_SUCCESS";
export const PATCH_TABLE_FAIL = "PATCH_TABLE_FAIL";

export const DELET_TABLE_SUCCESS = "DELET_TABLE_SUCCESS";
export const DELET_TABLE_FAIL = "DELET_TABLE_SUCCESS";

// export const MENDENGAR_WASIT1_BIRU_SUCCESS = "MENDENGAR_WASIT1_BIRU_SUCCESS";
// export const MENDENGAR_WASIT2_BIRU_SUCCESS = "MENDENGAR_WASIT2_BIRU_SUCCESS";
// export const MENDENGAR_WASIT3_BIRU_SUCCESS = "MENDENGAR_WASIT3_BIRU_SUCCESS";
// export const MENDENGAR_WASIT4_BIRU_SUCCESS = "MENDENGAR_WASIT4_BIRU_SUCCESS";
// export const MENDENGAR_WASIT5_BIRU_SUCCESS = "MENDENGAR_WASIT5_BIRU_SUCCESS";

// export const MENDENGAR_WASIT1_KUNING_SUCCESS = "MENDENGAR_WASIT1_KUNING_SUCCESS";
// export const MENDENGAR_WASIT2_KUNING_SUCCESS = "MENDENGAR_WASIT2_KUNING_SUCCESS";
// export const MENDENGAR_WASIT3_KUNING_SUCCESS = "MENDENGAR_WASIT3_KUNING_SUCCESS";
// export const MENDENGAR_WASIT4_KUNING_SUCCESS = "MENDENGAR_WASIT4_KUNING_SUCCESS";
// export const MENDENGAR_WASIT5_KUNING_SUCCESS = "MENDENGAR_WASIT5_KUNING_SUCCESS";

// export const MENDENGAR_WASIT1_BIRU_FAIL = "MENDENGAR_WASIT1_BIRU_SUCCESS";
// export const MENDENGAR_WASIT2_BIRU_FAIL = "MENDENGAR_WASIT2_BIRU_SUCCESS";
// export const MENDENGAR_WASIT3_BIRU_FAIL = "MENDENGAR_WASIT3_BIRU_SUCCESS";
// export const MENDENGAR_WASIT4_BIRU_FAIL = "MENDENGAR_WASIT4_BIRU_SUCCESS";
// export const MENDENGAR_WASIT5_BIRU_FAIL = "MENDENGAR_WASIT5_BIRU_SUCCESS";

// export const MENDENGAR_WASIT1_KUNING_FAIL = "MENDENGAR_WASIT1_KUNING_SUCCESS";
// export const MENDENGAR_WASIT2_KUNING_SUCCESS = "MENDENGAR_WASIT2_KUNING_SUCCESS";
// export const MENDENGAR_WASIT3_KUNING_SUCCESS = "MENDENGAR_WASIT3_KUNING_SUCCESS";
// export const MENDENGAR_WASIT4_KUNING_SUCCESS = "MENDENGAR_WASIT4_KUNING_SUCCESS";
// export const MENDENGAR_WASIT5_KUNING_SUCCESS = "MENDENGAR_WASIT5_KUNING_SUCCESS";

