export const Data=[
    {
        nama:"JONI",
        kelas:"APA",
        kontingen:"Jateng"
    },
    {
        nama:"JONA",
        kelas:"BPA",
        kontingen:"Jateng"
    },
    {
        nama:"JONO",
        kelas:"CPA",
        kontingen:"Jateng"
    },
    {
        nama:"JINI",
        kelas:"DPA",
        kontingen:"Jateng"
    },
    {
        nama:"JUNI",
        kelas:"DPA",
        kontingen:"Jateng"
    },
    {
        nama:"JONE",
        kelas:"DPA",
        kontingen:"Jateng"
    },
    {
        nama:"JONIS",
        kelas:"EPA",
        kontingen:"Jateng"
    },
    {
        nama:"JONES",
        kelas:"EPA",
        kontingen:"Jateng"
    },
    {
        nama:"JSON",
        kelas:"FPA",
        kontingen:"Jateng"
    },
    {
        nama:"JK",
        kelas:"GPA",
        kontingen:"Jateng"
    },
    {
        nama:"JONI",
        kelas:"API",
        kontingen:"Jateng"
    },
    {
        nama:"JONA",
        kelas:"BPI",
        kontingen:"Jateng"
    },
    {
        nama:"JONO",
        kelas:"CPI",
        kontingen:"Jateng"
    },
    {
        nama:"JINI",
        kelas:"DPI",
        kontingen:"Jateng"
    },
    {
        nama:"JUNI",
        kelas:"DPI",
        kontingen:"Jateng"
    },
    {
        nama:"JONE",
        kelas:"DPI",
        kontingen:"Jateng"
    },
    {
        nama:"JONIS",
        kelas:"EPI",
        kontingen:"Jateng"
    },
    {
        nama:"JONES",
        kelas:"EPI",
        kontingen:"Jateng"
    },
    {
        nama:"JSON",
        kelas:"FPI",
        kontingen:"Jateng"
    },
    {
        nama:"JK",
        kelas:"GPI",
        kontingen:"Jateng"
    },

]

export const Kelas =[
    {
        kelas:"ALL"
    },
    {
        kelas:"APA"
    },
    {
        kelas:"BPA"
    },
    {
        kelas:"CPA"
    },
    {
        kelas:"DPA"
    },
    {
        kelas:"EPA"
    },
    {
        kelas:"FPA"
    },
    {
        kelas:"GPA"
    },
    {
        kelas:"HPA"
    },
    {
        kelas:"IPA"
    },
    {
        kelas:"API"
    },
    {
        kelas:"BPI"
    },
    {
        kelas:"CPI"
    },
    {
        kelas:"DPI"
    },
    {
        kelas:"EPI"
    },
    {
        kelas:"FPI"
    },
    {
        kelas:"GPI"
    },
    {
        kelas:"HPI"
    },
    {
        kelas:"IPI"
    },

]